apiVersion: v1
kind: Service
metadata:
  name: clouddemo-sofi
  annotations:
    cloud.google.com/neg: '{"ingress": false}' # Disable NEG

spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: clouddemo-sofi
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddemo-sofi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clouddemo-sofi
  template:
    metadata:
      labels:
        app: clouddemo-sofi
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: clouddemo-sofi
        image: clouddemo-sofi
        ports:
          - containerPort: 80
        livenessProbe:      # Used by deployment controller
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 5
        readinessProbe:     # Used by Ingress/GCLB
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 256Mi
